//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evidencijaEntities : DbContext
    {
        public evidencijaEntities()
            : base("name=evidencijaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<djelatnik> djelatnik { get; set; }
        public virtual DbSet<vezaDjelatnikRad> vezaDjelatnikRad { get; set; }
        public virtual DbSet<vrstaRada> vrstaRada { get; set; }
    }
}
