//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrstaRada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vrstaRada()
        {
            this.vezaDjelatnikRad = new HashSet<vezaDjelatnikRad>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string boja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vezaDjelatnikRad> vezaDjelatnikRad { get; set; }
    }
}
